name: terraform-apply

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.14.0"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_APPLY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform init (no backend for now)
        run: terraform init -input=false -backend=false

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform validate
        run: terraform validate

      # - name: Terraform plan
      #   run: terraform plan -input=false -no-color -out=tfplan

      # - name: Terraform apply
      #   run: terraform apply -input=false -auto-approve tfplan
